// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Este `url` es el que usa la CLI de Prisma para las migraciones, y las
    // migraciones necesitan conexión DIRECTA: a través del pooler de Neon
    // el advisory lock de `migrate deploy` se queda colgado y falla con P1002.
    // La app sí usa el pooler (DATABASE_URL en lib/db.ts), que es lo correcto
    // en serverless. `directUrl` se eliminó en Prisma 7; el reemplazo es esto.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
